kind: pipeline
type: docker
name: default

steps:
- name: build
  image: golang
  commands:
  - go build
  - go test ./...

- name: publish
  image: drone-plugins/drone-snyk
  settings:
    repo: drone-plugins/drone-snyk
    auto_tag: true
    dockerfile: docker/Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
